openapi: 3.0.1
info:
  title: Python Microservice Template
  description: Python Microservice Template
  version: 1.0.0
servers:
- url: "/api"
paths:
  /hello:
    get:
      tags:
      - hello
      summary: returns hello
      description: |
        Returns a simple hello
      operationId: hello.testHello
      responses:
        200:
          description: hello obj
          content:
            application/json:
              schema:
                type: object
        400:
          description: bad input parameter
          content: {}
components:
  schemas:
    hello:
      type: object
      properties:
        hello:
          type: string
          example: hello-string